name: pipeline-main

on:
    workflow_dispatch:
    push:
        branches:
            - main
            - dev-0
jobs:
    main:
        uses: ddruk-landing-zone-0/ddruk_cicd_main/.github/workflows/python-gcp-main.yml@main
        secrets: inherit
        with:
            GCP_PROJECT_ID: hackathon0-project
            CLOUD_RUN_SERVICE: sample-react-server
            CLOUD_RUN_REGION: us-central1
            GAR_LOCATION: us-central1-docker.pkg.dev/hackathon0-project/react-server
            GAR_LOCATION_PREFIX: us-central1-docker.pkg.dev
            IMAGE_NAME: sample-react-server-image
            SERVICE_ACCOUNT: hackathon0-sa@hackathon0-project.iam.gserviceaccount.com
            DOCKER_FILE: Dockerfile.app
            CLOUD_RUN_RAM: 512Mi